apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: secret-lab

spec:
  replicas: 1

  selector:
    matchLabels:
      app: payment

  template:
    metadata:
      labels:
        app: payment

    spec:
      containers:
      - name: payment
        image: busybox

        command:
        - sh
        - -c
        - |
          echo "Application Started"

          echo "Current Token: $TOKEN"

          while true
          do
            if [ "$TOKEN" = "new-token" ]
            then
              echo "Authentication Successful"
            else
              echo "401 Unauthorized"
              echo "Token validation failed"
            fi

            sleep 10
          done

        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: TOKEN