apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
spec:
  restartPolicy: Never
  containers:
  - name: curl
    image: curlimages/curl
    command:
    - sh
    - -c
    - |
      while true
      do
        curl http://checkout-service
        sleep 2
      done